from django.urls import path
from apps.interactions.views import (
    EnrollmentCreateAPIView,
    EnrollmentDeleteAPIView,
    EnrollmentListAPIView,
    EnrollmentRetrieveAPIView,
    EnrollmentUpdateAPIView,
    LessonAnswerCreateAPIView,
    LessonAnswerDeleteAPIView,
    LessonAnswerListAPIView,
    LessonAnswerRetrieveAPIView,
    LessonAnswerUpdateAPIView,
    LessonQuestionCreateAPIView,
    LessonQuestionDeleteAPIView,
    LessonQuestionListAPIView,
    LessonQuestionRetrieveAPIView,
    LessonQuestionUpdateAPIView,
    LessonRateCreateAPIView,
    LessonRateDeleteAPIView,
    LessonRateListAPIView,
    LessonRateRetrieveAPIView,
    LessonRateUpdateAPIView,
    LessonResourceCreateAPIView,
    LessonResourceDeleteAPIView,
    LessonResourceListAPIView,
    LessonResourceRetrieveAPIView,
    LessonResourceUpdateAPIView,
    UserHomeworkAttemptCreateAPIView,
    UserHomeworkAttemptDeleteAPIView,
    UserHomeworkAttemptListAPIView,
    UserHomeworkAttemptRetrieveAPIView,
    UserHomeworkAttemptUpdateAPIView,
)

urlpatterns = [
    path("enrollments/", EnrollmentListAPIView.as_view(), name="enrollment-list"),
    path("enrollments/create/", EnrollmentCreateAPIView.as_view(), name="enrollment-create"),
    path("enrollments/<int:pk>/", EnrollmentRetrieveAPIView.as_view(), name="enrollment-single"),
    path("enrollments/update/<int:pk>/", EnrollmentUpdateAPIView.as_view(), name="enrollment-update"),
    path("enrollments/delete/<int:pk>/", EnrollmentDeleteAPIView.as_view(), name="enrollment-delete"),

    path("lesson-questions/", LessonQuestionListAPIView.as_view(), name="lesson-question-list"),
    path("lesson-questions/create/", LessonQuestionCreateAPIView.as_view(), name="lesson-question-create"),
    path("lesson-questions/<int:pk>/", LessonQuestionRetrieveAPIView.as_view(), name="lesson-question-single"),
    path("lesson-questions/update/<int:pk>/", LessonQuestionUpdateAPIView.as_view(), name="lesson-question-update"),
    path("lesson-questions/delete/<int:pk>/", LessonQuestionDeleteAPIView.as_view(), name="lesson-question-delete"),

    path("lesson-answers/", LessonAnswerListAPIView.as_view(), name="lesson-answer-list"),
    path("lesson-answers/create/", LessonAnswerCreateAPIView.as_view(), name="lesson-answer-create"),
    path("lesson-answers/<int:pk>/", LessonAnswerRetrieveAPIView.as_view(), name="lesson-answer-single"),
    path("lesson-answers/update/<int:pk>/", LessonAnswerUpdateAPIView.as_view(), name="lesson-answer-update"),
    path("lesson-answers/delete/<int:pk>/", LessonAnswerDeleteAPIView.as_view(), name="lesson-answer-delete"),

    path("lesson-resources/", LessonResourceListAPIView.as_view(), name="lesson-resource-list"),
    path("lesson-resources/create/", LessonResourceCreateAPIView.as_view(), name="lesson-resource-create"),
    path("lesson-resources/<int:pk>/", LessonResourceRetrieveAPIView.as_view(), name="lesson-resource-single"),
    path("lesson-resources/update/<int:pk>/", LessonResourceUpdateAPIView.as_view(), name="lesson-resource-update"),
    path("lesson-resources/delete/<int:pk>/", LessonResourceDeleteAPIView.as_view(), name="lesson-resource-delete"),

    path("lesson-rates/", LessonRateListAPIView.as_view(), name="lesson-rate-list"),
    path("lesson-rates/create/", LessonRateCreateAPIView.as_view(), name="lesson-rate-create"),
    path("lesson-rates/<int:pk>/", LessonRateRetrieveAPIView.as_view(), name="lesson-rate-single"),
    path("lesson-rates/update/<int:pk>/", LessonRateUpdateAPIView.as_view(), name="lesson-rate-update"),
    path("lesson-rates/delete/<int:pk>/", LessonRateDeleteAPIView.as_view(), name="lesson-rate-delete"),

    path("homework-attempts/", UserHomeworkAttemptListAPIView.as_view(), name="homework-attempt-list"),
    path("homework-attempts/create/", UserHomeworkAttemptCreateAPIView.as_view(), name="homework-attempt-create"),
    path("homework-attempts/<int:pk>/", UserHomeworkAttemptRetrieveAPIView.as_view(), name="homework-attempt-single"),
    path("homework-attempts/update/<int:pk>/", UserHomeworkAttemptUpdateAPIView.as_view(), name="homework-attempt-update"),
    path("homework-attempts/delete/<int:pk>/", UserHomeworkAttemptDeleteAPIView.as_view(), name="homework-attempt-delete"),
]