# Generated by Django 6.0.3 on 2026-03-30 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$")],
                verbose_name="phone",
            ),
        ),
    ]
