# Generated by Django 6.0.3 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_wallet_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stars_balance",
            field=models.PositiveIntegerField(default=0, verbose_name="stars balance"),
        ),
    ]
