# Generated by Django 6.0.3 on 2026-04-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_currency_course_price"),
        ("interactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonFavorite",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="courses.lesson",
                        verbose_name="lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson favorite",
                "verbose_name_plural": "lesson favorites",
                "unique_together": {("lesson", "user")},
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                ("watch_percent", models.PositiveSmallIntegerField(default=0, verbose_name="watch percent")),
                ("is_completed", models.BooleanField(default=False, verbose_name="is completed")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="completed at")),
                ("reward_granted", models.BooleanField(default=False, verbose_name="reward granted")),
                ("rewarded_stars", models.PositiveIntegerField(default=0, verbose_name="rewarded stars")),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progresses",
                        to="interactions.enrollment",
                        verbose_name="enrollment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to="courses.lesson",
                        verbose_name="lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "lesson progress",
                "verbose_name_plural": "lesson progresses",
                "unique_together": {("enrollment", "lesson")},
            },
        ),
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "progress_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="progress percentage"),
                ),
                ("completed_lessons", models.PositiveIntegerField(default=0, verbose_name="completed lessons")),
                ("total_lessons", models.PositiveIntegerField(default=0, verbose_name="total lessons")),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_progresses",
                        to="interactions.enrollment",
                        verbose_name="enrollment",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to="courses.module",
                        verbose_name="module",
                    ),
                ),
            ],
            options={
                "verbose_name": "module progress",
                "verbose_name_plural": "module progresses",
                "unique_together": {("enrollment", "module")},
            },
        ),
    ]
