from django.urls import path

from apps.courses.views import (
    CategoryRetrieveAPIView,
    CategoryCreateAPIView,
    CategoryDeleteAPIView,
    CategoryListAPIView,
    CategoryUpdateAPIView,
    TagCreateAPIView,
    TagDeleteAPIView,
    TagListAPIView,
    TagRetrieveAPIView,
    TagUpdateAPIView,
    CourseCreateAPIView,
    CourseDeleteAPIView,
    CourseListAPIView,
    CourseRetrieveAPIView,
    CourseUpdateAPIView,
    CourseTagCreateAPIView,
    CourseTagDeleteAPIView,
    CourseTagListAPIView,
    CourseTagRetrieveAPIView,
    CourseTagUpdateAPIView,
    ModuleCreateAPIView,
    ModuleDeleteAPIView,
    ModuleListAPIView,
    ModuleRetrieveAPIView,
    ModuleUpdateAPIView,
    LessonCreateAPIView,
    LessonDeleteAPIView,
    LessonListAPIView,
    LessonRetrieveAPIView,
    LessonUpdateAPIView,
)

urlpatterns = [
    path("categories/",CategoryListAPIView.as_view(),name="category-list"),
    path("category/<int:pk>",CategoryRetrieveAPIView.as_view(),name="category-single"),
    path("category/update/<int:pk>",CategoryUpdateAPIView.as_view(),name="category-update"),
    path("category/delete/<int:pk>",CategoryDeleteAPIView.as_view(),name="category-delete"),
    path("category/create/",CategoryCreateAPIView.as_view(),name="category-create"),
    path("tags/",TagListAPIView.as_view(),name="tag-list"),
    path("tag/<int:pk>",TagRetrieveAPIView.as_view(),name="tag-single"),
    path("tag/update/<int:pk>",TagUpdateAPIView.as_view(),name="tag-update"),
    path("tag/delete/<int:pk>",TagDeleteAPIView.as_view(),name="tag-delete"),
    path("tag/create/",TagCreateAPIView.as_view(),name="tag-create"),
    path("courses/", CourseListAPIView.as_view(), name="course-list"),
    path("course/<int:pk>", CourseRetrieveAPIView.as_view(), name="course-single"),
    path("course/create/", CourseCreateAPIView.as_view(), name="course-create"),
    path("course/update/<int:pk>", CourseUpdateAPIView.as_view(), name="course-update"),
    path("course/delete/<int:pk>", CourseDeleteAPIView.as_view(), name="course-delete"),
    path("course-tags/", CourseTagListAPIView.as_view(), name="coursetag-list"),
    path("course-tag/<int:pk>", CourseTagRetrieveAPIView.as_view(), name="coursetag-single"),
    path("course-tag/create/", CourseTagCreateAPIView.as_view(), name="coursetag-create"),
    path("course-tag/update/<int:pk>", CourseTagUpdateAPIView.as_view(), name="coursetag-update"),
    path("course-tag/delete/<int:pk>", CourseTagDeleteAPIView.as_view(), name="coursetag-delete"),
    path("modules/", ModuleListAPIView.as_view(), name="module-list"),
    path("module/<int:pk>", ModuleRetrieveAPIView.as_view(), name="module-single"),
    path("module/create/", ModuleCreateAPIView.as_view(), name="module-create"),
    path("module/update/<int:pk>", ModuleUpdateAPIView.as_view(), name="module-update"),
    path("module/delete/<int:pk>", ModuleDeleteAPIView.as_view(), name="module-delete"),
    path("lessons/", LessonListAPIView.as_view(), name="lesson-list"),
    path("lesson/<int:pk>", LessonRetrieveAPIView.as_view(), name="lesson-single"),
    path("lesson/create/", LessonCreateAPIView.as_view(), name="lesson-create"),
    path("lesson/update/<int:pk>", LessonUpdateAPIView.as_view(), name="lesson-update"),
    path("lesson/delete/<int:pk>", LessonDeleteAPIView.as_view(), name="lesson-delete"),
]