# Generated by Django 6.0.3 on 2026-04-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_name_en_category_name_ru_category_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='online_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Online URL (YouTube, Vimeo, etc.)'),
        ),
    ]
