# Generated by Django 6.0.3 on 2026-04-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_online_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('article', 'Article'), ('file', 'File'), ('homework', 'Homework')], max_length=50, verbose_name='type'),
        ),
    ]
