# Generated by Django 6.0.3 on 2026-04-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.tag', verbose_name='tags'),
        ),
        migrations.DeleteModel(
            name='CourseTag',
        ),
    ]
