# Generated by Django 6.0.3 on 2026-04-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tags_delete_coursetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('uzs', 'uzs'), ('usd', 'usd'), ('eur', 'eur'), ('rub', 'rub')], default='uzs', max_length=20, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
        ),
    ]
