# Generated by Django 6.0.3 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(fields=("user", "course"), name="unique_user_course_order"),
        ),
    ]
