# Generated by Django 6.0.3 on 2026-03-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="file_url",
        ),
        migrations.AddField(
            model_name="media",
            name="file",
            field=models.FileField(
                default="file.com/file", max_length=500, upload_to="media/", verbose_name="File URL"
            ),
            preserve_default=False,
        ),
    ]
