# Generated by Django 6.0.3 on 2026-04-03 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_media_file_url_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='common.country'),
            preserve_default=False,
        ),
    ]
